### ISSUE TITLE
Error when creating Chromunity object

### ISSUE THREAD

**Issue by hackkr** [mskilab-org/chromunity#15]
Hello,
I'm trying to run chromunity on some prokaryotic pore-c data. I'm working through the tutorial, and am getting an error message when I try to create a Chromunity object for sliding window chromunity that subject contains `Error: subscript contains out-of-bounds indices`. Any tips for troubleshooting would be appreciated.

Code:
```
sliding_chrom = sliding_window_chromunity(concatemers = this_gr, resolution = 2e3, window.size = 2e4, take_sub_sample = TRUE, chr  = "NC_017276.1", subsample.frac = 0.5, mc.cores = 1)
```
my genome is much smaller, and the resolution is apprpirate for the cutter used. I tried the settings used in the tutorial and the error persists. 
 
GRanges object containing contatemers (converted from parquet files):
```
GRanges object with 378891 ranges and 2 metadata columns:
              seqnames          ranges strand |    read_idx         cid
                 <Rle>       <IRanges>  <Rle> | <character> <character>
       [1] NC_017276.1 1946799-1947341      * |           1           1
       [2] NC_017276.1   814241-814621      * |           2           2
       [3] NC_017276.1   739879-740131      * |           3           3
       [4] NC_017276.1   796003-796199      * |           3           3
       [5] NC_017276.1 2219714-2220398      * |           4           4
       ...         ...             ...    ... .         ...         ...
  [378887] NC_017276.1   435942-436104      * |      262316      262316
  [378888] NC_017276.1 2266975-2267170      * |      262317      262317
  [378889] NC_017276.1   851082-851188      * |      262318      262318
  [378890] NC_017276.1 2345474-2345889      * |      262318      262318
  [378891] NC_017276.1 2268182-2268366      * |      262319      262319
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
```

The error traceback:
```
16. stop(wmsg(...), call. = FALSE)
15. .subscript_error("subscript contains out-of-bounds indices")
14. NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, allow.NAs = allow.NAs)
13. NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, allow.NAs = allow.NAs)
12. normalizeSingleBracketSubscript(i, x, as.NSBS = TRUE)
11. extractROWS(x, i)
10. extractROWS(x, i)
9. subset_along_ROWS(x, i, drop = drop)
8. windows[j]
7. windows[j]
6. withCallingHandlers(expr, warning = function(w) if (inherits(w,classes)) tryInvokeRestart("muffleWarning"))
5. suppressWarnings({which.gr = windows[j] these.cids = (concatemers %&% which.gr)$cid this.pc.gr = concatemers %Q% (cid %in% these.cids) ...
4. FUN(X[[i]], ...)
3. lapply(X = X, FUN = FUN, ...)
2. mclapply(1:length(windows), mc.cores = mc.cores, function(j) {
      suppressWarnings({
      which.gr = windows[j] these.cids = (concatemers %&% which.gr)$cid ...
1.sliding_window_chromunity(concatemers = final, resolution = 2000, window.size = 20000, take_sub_sample = TRUE, chr = "NC_017276.1", subsample.frac = 0.5, mc.cores = 1)
```

**Comment by jameson-orvis** [comment]
Hi! Fascinating that you are doing Pore-C on a prokaryotic genome! I would try increasing your resolution and window size, you may theoretically be able to resolve higher order contacts at that resolution given the distribution of cut sites but it is very unlikely you have the sequencing depth required. I believe this error comes about simply if Chromunity discovers zero communities. I'd first try resolution = 10000 and window.size = 2e6 which are parameters we use most often. If that doesn't work maybe you could share your concatemers file and I could look into it more.

**Comment by hackkr** [comment]
Hi! Thanks so much for your quick response! I have tried creating the object with higher resolutions (both what you recommended above and the resolution used for the demo data) and I still get the same error. The genome is only 2.5 Mb, so I think we'd want to eventually have enough depth for a smaller window size, but this is a preliminary sequencing run.  I'd be happy to share the concatemers file - that'd be the gRanges I'm assuming?
[hackley_concatemers.csv.gz](https://github.com/mskilab-org/chromunity/files/15205026/hackley_concatemers.csv.gz)


I wondered if it was due to missing metadata, but setting seqlengths() doesn't help either.

**Comment by jameson-orvis** [comment]
Hi, I believe I tracked down the issue. I added logic to just create bins based on the region the concatemers span if you pass in NULL as a genome, rather than binning the output of hg_seqlengths(). Try pulling the lastest change and running `sliding_window_chromunity(concatemers = this_gr, resolution=10000, chr='NC_017276.1', window.size=2e6, genome=NULL) `

**Comment by hackkr** [comment]
Hello,

I re-installed chromunity from the master branch and am running into a different error. `packageVersion("chromunity")` gives 0.0.2

Traceback:
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqinfo’ for signature ‘"NULL"’
6. stop(gettextf("unable to find an inherited method for function %s for signature %s",
sQuote(fdef@generic), sQuote(cnames)), domain = NA)
5. (function (classes, fdef, mtable){methods <- .findInheritedMethods(classes, fdef, mtable)if (length(methods) == 1L) ...
4. seqinfo(si)
3. si2gr(gr)
2. gr.tile(hg_seqlengths(genome = genome), window.size/2)
1. sliding_window_chromunity(concatemers = this_gr, resolution = 10000, chr = "NC_017276.1", window.size = 2e+06, genome = NULL)
```

setting genome(this_gr) doesn't help.
```
genome(this_gr) <- "GCF_000189555.1"
```

**Comment by jameson-orvis** [comment]
Can you give the output of sessionInfo()? If possible, could you run sliding_window_chomunity in debug mode and check the region variable? It should simply be a GRange that looks like this:

<img width="382" alt="image" src="https://github.com/mskilab-org/chromunity/assets/59614493/04807da6-bc72-47f0-8938-3450e52643db">

You could also passing in region as an input, so running `sliding_window_chromunity(concatemers = this_gr, resolution = 10000, chr = "NC_017276.1", window.size = 2e+06, genome = NULL, region=GRanges('NC_017276.1:1-2522992'))` Sorry for the hassle with this, thank you for giving the impetus to update the package to handle non-human genomes!

**Comment by hackkr** [comment]
Clearing my environment and pulling chromunity again seems to have resolved the issue! I can successfully run `sliding_window_chromunity` on my data. I do get a warning message: 

```
Chromunity 2024-05-13 11:20:36: Taking sub-sample with fraction 0.5
Warning: Column 'V1' does not exist to removeChromunity 2024-05-13 11:21:12: Analyzing gr.sums associated with 6 concatemer communities to generate binsets
```

I'm so thankful for your assistance, and excited to be able to use this tool. I did have a couple questions about RE chromunity in a prokaryotic context. Would It be best if I opened a new issue?

**Comment by hackkr** [comment]
Could you clarify what the tutorial means by "effective" distance for interchromosomal bins in the `annotate()` function? The default setting is larger than my genome. 

I'm generally a little unsure how to determine appropriate region size for resolution and sliding windows. The cutter I used generates ~11,000 fragments with an N50 of 382 bps. The genome is 2.5 Mb. With 3C-seq we typically have a reliable resolution between 2-5kb. I know that read depth will be limiting for my preliminary analysis, but I'd like to get eventually get enough reads to have similar a resolution for Chromunity. 

When I set `sliding_window_chromunity(window.size=) ` too small, I get the error `object 'tix' not found`. I assume this has something to do with insufficient reads and a sparce table/matrix?

**Comment by jameson-orvis** [comment]
Hi! Sorry for my delayed response, I have been away the last 2 weeks but I will get to your messages. It is great that sliding window runs for you!

The effective interchromosomal distance is the value which is used in the first Synergy GLM when evaluating the extent to which the number of concatemers which hit a given sub-binset deviates from an expected background. That is, if a sub-binset spans multiple chromsomes, the GLM treats it equivalently as if it were a sub-binset which spanned 1e9 bases on one chromosome. It is a relatively arbitrary high value because interchromosomal contacts should be rare. For your purposes this value should be irrelevant though.

For reference the window size used in the paper for GM12878 is 2 Mb, which is almost the size of your entire genome. You could probably run it all in one big window. You are correct that the tix error is a result of sparsity, essentially there is no community discovered in a given sliding window at all. I would generally skew towards larger Mb scale windows.

**Comment by hackkr** [comment]
excellent, thank you for the explanation! I'm closing this issue for now,
as I have another open issue.
