### ISSUE TITLE
input data of the tutorial

### ISSUE THREAD

**Issue by LuJiansen** [mskilab-org/chromunity#2]
Hi @mskilab ,
Could you please share the input data of the tutorial? I haven't found the format of some files used in the tutorial, such as 'Nlaiii.frags.hg38.rds' and 'gc.38.rds'. It would be better if these files are available.
Since the #1 was closed, I opened this new issue
Thank you very much!

**Comment by asd1289** [comment]
@LuJiansen Yes, I am working on it and will have it ready early next week. Thanks

**Comment by asd1289** [comment]
These are available within the tutorial that is up to date now.
